### ISSUE TITLE
Clarify what it means to clarify how objects were initialized

### ISSUE THREAD

**Issue by nhayden** [Bioconductor/BiocCheck.old#43]
There's a CONSIDERation, e.g.,

```
* CONSIDER: Clarifying how objects miRNA, Target_Gene_.Entrez_ID.,
      x (used in addMirEffect, mirTarget, plotLines) were initialized.
      Maybe they are part of a data set loaded with data(), or perhaps
      part of an object referenced in with() or within().
```

But to a novice contributor this is fairly opaque.

In this example, the instances in question are using `subset` on `data.frame`s and the symbols it doesn't like are column names from the data.frame.

**Comment by dtenenba** [comment]
For example, if the objects were initialized via loading something with data(), I don't know how that can be "clarified". Seems like this code was originally written in cases where it was possible to clarify, but I can't exactly remember what/how right now....so either remove this or provide more useful instructions.

**Comment by llrs** [comment]
I am now considering to clarify an object but I don't know how to clarify an object reference. If it is not removed, could someone provide some help/guidance about how to clarify an object origin?

**Comment by mtmorgan** [comment]
Ask on the [Bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list (you'll have to subscribe, but you'll do that anyway when submitting the package) and provide some information about the object that is causing this note.

**Comment by llrs** [comment]
@mtmorgan I posted an issue on the bioconductor BiocCheck repository. But for submitting it to the mailing list, I will wait a little, in case I manage to avoid parallel computing (with foreach) by doing SQLite queries.

**Comment by mtmorgan** [comment]
I'll close the issue and delete this repository.
